export const dynamic = "force-dynamic"
import "@/styles/globals.css"
import { ReactScan } from "@/components/ReactScanComponent"
import { env } from "@/env"
import { TRPCReactProvider } from "@/trpc/react"
import { DevOnly } from "@redbruno/isdev"
import type { Metadata } from "next"
import { Geist } from "next/font/google"

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
})

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<head>
				<DevOnly isDev={env.NODE_ENV}>
					<ReactScan />
				</DevOnly>
			</head>
			<body>
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	)
}
